### ISSUE TITLE
What is the purpose of the "edit" button in the bookshelf?

### ISSUE THREAD

**Issue by kelson42** [automactic/Kiwix#11]
In my case, nothing happens by clicking on it.

**Comment by automactic** [comment]
Nothing, I just added this as a place holder, so that the tabs will be in the middle.

**Comment by kelson42** [comment]
OK, might be replace with an empty box/text?

**Comment by automactic** [comment]
Yes, replaced with empty button.

**Comment by kelson42** [comment]
THX
