### ISSUE TITLE
In Bookshelf, language filter does not apply immediatly

### ISSUE THREAD

**Issue by kelson42** [automactic/Kiwix#12]
If filtering by language has changed, the list should be automatically reloaded by clicking on "back"

**Comment by automactic** [comment]
yes, that's a problem I also noticed. 

Another things is when the first time the book catalogue is loaded, if you go to language filter, nothing will show up. I know why, but don't know how to fix (yet).

**Comment by kelson42** [comment]
yes I confirm the bug of empty list

**Comment by kelson42** [comment]
Looks good now, have you fixed that bugs?

**Comment by automactic** [comment]
I think this should already be fixed in the current build, please check.

**Comment by kelson42** [comment]
Yes!
