### ISSUE TITLE
Write full language name in Bookshelf

### ISSUE THREAD

**Issue by kelson42** [automactic/Kiwix#14]
In the bookshelf, the ISO code is given instead the real name of languages. People don't know really well about ISO codes and prefer to have the real name of the language (in English).

**Comment by kelson42** [comment]
This is fixed, THX!

**Comment by kelson42** [comment]
Unfortunately a few ISO codes are not correctly matched (like "eml" for example). I guess you use the iOS SDK and it does not work for all languages. Probably a complementary custom matching table is necesary.

**Comment by automactic** [comment]
Are you referring to some of the unreplaced ISO codes? There is no "eml" in the [list](https://sourceforge.net/p/kiwix/other/ci/master/tree/youtube/ISO-639-2_utf-8.txt) you gave me earlier.

**Comment by kelson42** [comment]
OK, for eml, this seems ot be complicated... please just hide this languages/content

**Comment by automactic** [comment]
What about other unmatched codes? Like arz. Hide them all? There are a lot of'em.

**Comment by kelson42** [comment]
Remove everything where the ISO code does not match, we can see later if someone complains about that.

**Comment by kelson42** [comment]
Looks to be perfectly fixed now :)
