### ISSUE TITLE
Downloader does not check if enough place on the filesystem

### ISSUE THREAD

**Issue by kelson42** [automactic/Kiwix#15]
I tried to download a big gutenberg file and the download got stuck. I guess the app does not check if the device has enough free space.

Two things should be done here:
* At the download time check if enough free space
* At the bookshelf display time, grey out content which can not be downloaded due to lack of free storage

**Comment by kelson42** [comment]
Stopping these downloads seems also to be impossible.

**Comment by automactic** [comment]
Check BUILD 20150609 to see if the problem is fixed.

**Comment by kelson42** [comment]
Looks good to me, but message should be "Not enough space" instead of "Space not enough."

**Comment by automactic** [comment]
Ah, yes.

**Comment by automactic** [comment]
Should have already been fixed in build 20150613, please check.

**Comment by kelson42** [comment]
OK, I close this because now that the biggest file can not anymore be downloaded, this might be a little bit challenging to test it. Will re-open the ticket if necessary.
