### ISSUE TITLE
Change default bookshelf filter

### ISSUE THREAD

**Issue by kelson42** [automactic/Kiwix#16]
80% of user are only interested in content in their language. In particular the native English speakers. For this reason the default bookshelf filter should display books in all languages, but only the one in the default iOS language.

**Comment by automactic** [comment]
Do you think (maybe in the future), we can have different xml link for different languages? Because now we need to download and process the whole catalogue, waisting a lot of time and processing power. 

When you refresh the catalogue, during processing, the CPU is 99% utilized.

**Comment by kelson42** [comment]
I'll try to provide an API to avoid to download everything each time.

**Comment by kelson42** [comment]
Will also probably switch to OPDS

**Comment by kelson42** [comment]
The users get now an invitation to filter with the language of the device. This looks good to me.
