### ISSUE TITLE
Notification should be send at the end of a download

### ISSUE THREAD

**Issue by kelson42** [automactic/Kiwix#17]
At the end of a download a notications (sounds, widget, ...) should be thrown to avert the user that the download is finished. I would allow tend to think that this would be good to route the user to the "local' bookshelf, or maybe even better directly load the welcome page.

**Comment by automactic** [comment]
Yes, I also have this in mind. Load the welcome page is a good idea.

**Comment by automactic** [comment]
Actions of notification to be added

**Comment by automactic** [comment]
Notification actions to be added.

**Comment by automactic** [comment]
Check this in BUILD 20150627. Now it just notify the user, but having no actions in the notification. I have done some coding and research to implement the actions (open book catalogue and open main page), but there has been some problems, and I need some structure changes in class design to fix this. Why don't we leave it like this (just plain notification without actions) in the first version?

**Comment by kelson42** [comment]
Unfortunately, I don't see any notification at the end of a download on my device.

**Comment by kelson42** [comment]
sorry, I confirm it works.
