### ISSUE TITLE
Filter out ZIM files without languages metadata

### ISSUE THREAD

**Issue by kelson42** [automactic/Kiwix#19]
This generates a "strange" special "case" (N/A in the bookshelf) which is not easy to understand by the end users. These files should be filter out because ZIM files must have a language and therefore these files are "not compliant" ZIM files. In fact they are old files, so we can remove them without any big consequence.

**Comment by automactic** [comment]
Maybe we should just hide all codes not appearing in the ISO list.

**Comment by kelson42** [comment]
yes

**Comment by kelson42** [comment]
fixed
