### ISSUE TITLE
Autoload library if no ZIM available

### ISSUE THREAD

**Issue by kelson42** [automactic/Kiwix#2]
At the first start (or even later), if no ZIM available, the bookshelf (with the "all" tab) should be displayed.

**Comment by automactic** [comment]
Yes, also something I want to do.

**Comment by automactic** [comment]
Done, check it out in the next beta.

**Comment by kelson42** [comment]
Great, I assume this is well implemented :) I close already the ticket.

**Comment by kelson42** [comment]
It seems this does not work anymore. I re-open the bug.

**Comment by kelson42** [comment]
works again
