### ISSUE TITLE
Align bookshelf language labels

### ISSUE THREAD

**Issue by kelson42** [automactic/Kiwix#20]
In the bookshelf, content are sorted by language. For each language, you have the language label followed by the content files in that language. Unfortunately, the language labels are not aligned on the left with the icons, they are too much on the right. These labels should be aligned with the content icons, or maybe even a little bit more on the left.

**Comment by automactic** [comment]
The labels' place are automatically placed. But their position are customizable by providing a header. 

I think it looks fine in the way they are positioned now, if we move the language labels too left, they would be on the very edge of the screen. I also don't want to move favicon right, that means even smaller fonts for project gutenberg books.

**Comment by kelson42** [comment]
OK, I close the ticket.
