### ISSUE TITLE
Reading history is not recorded when tapped on a link in an article.

### ISSUE THREAD

**Issue by automactic** [automactic/Kiwix#27]
I am wondering whether parseURL function can convert a url to its title
Or record the the title in html dom.

**Comment by kelson42** [comment]
Strange, the webview proposes probably history navigation methods, so if you use them then it should work automatically. Hope you are not re-implementing a history manager on your own.

**Comment by automactic** [comment]
No, I meant my own history recording system, used to show the time (1 min ago, etc) after each article in bookmark.
