### ISSUE TITLE
Rename Bookshelf tabs

### ISSUE THREAD

**Issue by kelson42** [automactic/Kiwix#3]
I would write "online" instead of "all", it's send more clear that you need to download them.

**Comment by automactic** [comment]
If change to online, do you feel we should remove downloaded books in the "online" tab? They are no longer needed to download, but still sort of "online"? What about books that are downloading? Not so sure about this. Let me rethink if there is a better way.

**Comment by kelson42** [comment]
To answer your question, "yes" download books should IMOnot appear in the "online" tab. This is at least how works the dekstop version.

**Comment by automactic** [comment]
what about those in the process of downloading?

**Comment by kelson42** [comment]
hmm, not easy to answer, but I would tend to move them in the local/downloaded tab.

**Comment by automactic** [comment]
Lets put:
- in the cloud books + is downloading books in "Online"
- downloaded books + is downloading books in "Downloaded"

I also want to change "Online" and "Downloaded" to icons.

**Comment by kelson42** [comment]
fixed
