### ISSUE TITLE
Some articles are missing in latest DE wikipedia with images ZIM file

### ISSUE THREAD

**Issue by norabine** [automactic/Kiwix#44]
E.g. Article "VFB Stuttgart"

**Comment by kelson42** [comment]
https://de.wikipedia.org/wiki/VFB_Stuttgart does not exist. but https://de.wikipedia.org/wiki/VfB_Stuttgart does, in the ZIM file too. I think you hit here one of the current limitation of the ZIM file format which is that the suggestions system is mostly case sensitive.

**Comment by norabine** [comment]
Great. Works. You can close now 2 open problems.(missing galeries images and missing articles)

Von meinem iPad gesendet

**Comment by kelson42** [comment]
OK. I have open a ticket on openzim side which explains pretty in detail the problem:
https://phabricator.wikimedia.org/T108536
