### ISSUE TITLE
Improve "about"

### ISSUE THREAD

**Issue by kelson42** [automactic/Kiwix#8]
The about should give more information and be better presented
* bigger font
* list of libraries
* contact address
* ...

**Comment by automactic** [comment]
Do you have a list of libraries somewhere?

**Comment by automactic** [comment]
Please check the new about in BUILD 20150627.

**Comment by kelson42** [comment]
Here is the credit files for the desktop version https://sourceforge.net/p/kiwix/kiwix/ci/master/tree/kiwix/chrome/locale/branding/credits.html

**Comment by kelson42** [comment]
OK, looks good to me. The contact email should be "contact+ios@kiwix.org, I was not able to verify if this is OK.
